### ISSUE TITLE
Issues from Code review

### ISSUE THREAD

**Issue by mohamedismail86** [rengaswa-dv/github-for-developers-9#8]
1. searchBy field should be dynamic and add more variables
2. Remove Wait functions

**Comment by rengaswa-dv** [comment]
Both issues has been fixed. hence closing this bug

**Comment by mohamedismail86** [comment]
Hi Naga,

I have just reviewed your code and looks Wait function has been removed in only one place.
Please all the places and revert to me.
Reopening this issue.

**Comment by rengaswa-dv** [comment]
changes has been made as requested
